### ISSUE TITLE
fix jenkins startup

### ISSUE THREAD

**Issue by bdangit** [bdangit/hab-plans#1]
jenkins on startup is missing libgcc_s.so.1

```
jenkins(O): Sep 13, 2016 6:31:24 AM hudson.util.BootFailure publish
jenkins(O): SEVERE: Failed to initialize Jenkins
jenkins(O): hudson.util.AWTProblem: java.lang.UnsatisfiedLinkError: /hab/pkgs/core/jdk8/8u102/20160810135345/jre/lib/amd64/libfontmanager.so: libgcc_s.so.1: cannot open shared object file: No such file or directory
jenkins(O):     at hudson.WebAppMain.contextInitialized(WebAppMain.java:187)
jenkins(O):     at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
jenkins(O):     at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
jenkins(O):     at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
jenkins(O):     at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
jenkins(O):     at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
jenkins(O):     at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
jenkins(O):     at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
jenkins(O):     at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
jenkins(O):     at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
jenkins(O):     at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
jenkins(O):     at org.eclipse.jetty.server.Server.start(Server.java:387)
jenkins(O):     at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
jenkins(O):     at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
jenkins(O):     at org.eclipse.jetty.server.Server.doStart(Server.java:354)
jenkins(O):     at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
jenkins(O):     at winstone.Launcher.<init>(Launcher.java:152)
jenkins(O):     at winstone.Launcher.main(Launcher.java:352)
jenkins(O):     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins(O):     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins(O):     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins(O):     at java.lang.reflect.Method.invoke(Method.java:498)
jenkins(O):     at Main._main(Main.java:246)
jenkins(O):     at Main.main(Main.java:91)
jenkins(O): Caused by: java.lang.UnsatisfiedLinkError: /hab/pkgs/core/jdk8/8u102/20160810135345/jre/lib/amd64/libfontmanager.so: libgcc_s.so.1: cannot open shared object file: No such file or directory
jenkins(O):     at java.lang.ClassLoader$NativeLibrary.load(Native Method)
jenkins(O):     at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
jenkins(O):     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
jenkins(O):     at java.lang.Runtime.loadLibrary0(Runtime.java:870)
jenkins(O):     at java.lang.System.loadLibrary(System.java:1122)
jenkins(O):     at sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:61)
jenkins(O):     at java.security.AccessController.doPrivileged(Native Method)
jenkins(O):     at sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
jenkins(O):     at sun.font.SunFontManager$1.run(SunFontManager.java:339)
jenkins(O):     at java.security.AccessController.doPrivileged(Native Method)
jenkins(O):     at sun.font.SunFontManager.<clinit>(SunFontManager.java:335)
jenkins(O):     at java.lang.Class.forName0(Native Method)
jenkins(O):     at java.lang.Class.forName(Class.java:348)
jenkins(O):     at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:82)
jenkins(O):     at java.security.AccessController.doPrivileged(Native Method)
jenkins(O):     at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
jenkins(O):     at java.awt.Font.getFont2D(Font.java:491)
jenkins(O):     at java.awt.Font.getFamily(Font.java:1220)
jenkins(O):     at java.awt.Font.getFamily_NoClientCode(Font.java:1194)
jenkins(O):     at java.awt.Font.getFamily(Font.java:1186)
jenkins(O):     at java.awt.Font.toString(Font.java:1683)
jenkins(O):     at hudson.util.ChartUtil.<clinit>(ChartUtil.java:255)
jenkins(O):     at hudson.WebAppMain.contextInitialized(WebAppMain.java:186)
jenkins(O):     ... 23 more
jenkins(O):
jenkins(O): Sep 13, 2016 6:31:25 AM org.eclipse.jetty.util.log.JavaUtilLog info
jenkins(O): INFO: Started w.@6d6bc158{/,file:/hab/svc/jenkins/var/war/,AVAILABLE}{/hab/svc/jenkins/var/war}
jenkins(O): Sep 13, 2016 6:31:25 AM org.eclipse.jetty.util.log.JavaUtilLog info
jenkins(O): INFO: Started ServerConnector@672f11c2{HTTP/1.1}{0.0.0.0:8080}
jenkins(O): Sep 13, 2016 6:31:25 AM org.eclipse.jetty.util.log.JavaUtilLog info
jenkins(O): INFO: Started @9198ms
jenkins(O): Sep 13, 2016 6:31:25 AM winstone.Logger logInternal
jenkins(O): INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled

```

**Comment by bdangit** [comment]
https://github.com/bdangit/hab-plans/commit/8dab0c033be0422a40650a5641b2a201e78e36d9

fixed.  needed to add in LD_LIBRARY_PATH https://github.com/bdangit/hab-plans/blob/master/jenkins/hooks/run#L8-L9

**Comment by juliencauwet** [comment]
Hi bdangit,
I know this issue is a bit old but I have the exact same issue when I try to start my jenkins on my debian server except that the files missing are different.
Could you please explain a bit further the solution?
Many thanks in advance.
Julien

Below the trace:

`Apr 01, 2019 2:26:07 PM hudson.util.BootFailure publish
SEVERE: Failed to initialize Jenkins
hudson.util.AWTProblem: java.lang.UnsatisfiedLinkError: /home/linuxbrew/.linuxbrew/Cellar/openjdk/1.8.0-181/jre/lib/amd64/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:957)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:922)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:365)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:415)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at winstone.Launcher.<init>(Launcher.java:184)
	at winstone.Launcher.main(Launcher.java:354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Main._main(Main.java:375)
	at Main.main(Main.java:151)
Caused by: java.lang.UnsatisfiedLinkError: /home/linuxbrew/.linuxbrew/Cellar/openjdk/1.8.0-181/jre/lib/amd64/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
	at sun.font.SunFontManager$1.run(SunFontManager.java:339)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<clinit>(SunFontManager.java:335)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:82)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.awt.Font.getFont2D(Font.java:491)
	at java.awt.Font.getFamily(Font.java:1220)
	at java.awt.Font.getFamily_NoClientCode(Font.java:1194)
	at java.awt.Font.getFamily(Font.java:1186)
	at java.awt.Font.toString(Font.java:1683)
	at hudson.util.ChartUtil.<clinit>(ChartUtil.java:260)
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:192)
	... 24 more
`

**Comment by bdangit** [comment]
Hi @juliencauwet, it looks like you are not using Habitat otherwise this error is already fixed in `core`. 

Assuming you are not using Habitat, in your error logs, it looks like you are missing a shared lib or two or more!

Can you check if you have:
- libfreetype.so.6
- libfontmanager.so

I normally use `ldd /path/to/lib` to see if the libs dependencies are all satisfied.  You can also use `ldd` against the binary as well also make sure it has all the libs. 

Hope this helps.
