### ISSUE TITLE
error in build v8 

### ISSUE THREAD

**Issue by bdangit** [bdangit/hab-plans#5]
``` bash
Hint: You can raise verbosity (-vv) to see the output of failed commands.

Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/hab/pkgs/core/python2/2.7.12/20160926154224/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/hab/pkgs/core/python2/2.7.12/20160926154224/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
[2] v8(do_build)> tools/dev/v8gen.py -vv x64.release -- linux_use_bundled_binutils=false
  ################################################################################
/hab/pkgs/core/python2/2.7.12/20160926154224/bin/python -u tools/mb/mb.py gen -f infra/mb/mb_config.pyl -m developer_default -b x64.release out.gn/x64.release

  Writing """\
  is_debug = false
  target_cpu = "x64"
  """ to /hab/cache/src/v8-5.6.39/out.gn/x64.release/args.gn.

  /hab/cache/src/v8-5.6.39/buildtools/linux64/gn gen out.gn/x64.release --check
    -> returned 1
  ERROR at //build/config/linux/pkg_config.gni:85:17: Script returned non-zero exit code.
      pkgresult = exec_script(pkg_config_script, args, "value")
                  ^----------
  Current dir: /hab/cache/src/v8-5.6.39/out.gn/x64.release/
  Command: python -- /hab/cache/src/v8-5.6.39/build/config/linux/pkg-config.py -s /hab/cache/src/v8-5.6.39/build/linux/debian_wheezy_amd64-sysroot -a x64 glib-2.0 gmodule-2.0 gobject-2.0 gthread-2.0
  Returned 1.
  stderr:

  Traceback (most recent call last):
    File "/hab/cache/src/v8-5.6.39/build/config/linux/pkg-config.py", line 219, in <module>
      sys.exit(main())
    File "/hab/cache/src/v8-5.6.39/build/config/linux/pkg-config.py", line 138, in main
      prefix = GetPkgConfigPrefixToStrip(args)
    File "/hab/cache/src/v8-5.6.39/build/config/linux/pkg-config.py", line 80, in GetPkgConfigPrefixToStrip
      env=os.environ)
    File "/hab/pkgs/core/python2/2.7.12/20160926154224/lib/python2.7/subprocess.py", line 567, in check_output
      process = Popen(stdout=PIPE, *popenargs, **kwargs)
    File "/hab/pkgs/core/python2/2.7.12/20160926154224/lib/python2.7/subprocess.py", line 711, in __init__
      errread, errwrite)
    File "/hab/pkgs/core/python2/2.7.12/20160926154224/lib/python2.7/subprocess.py", line 1343, in _execute_child
      raise child_exception
  OSError: [Errno 2] No such file or directory

  See //build/config/linux/BUILD.gn:90:3: whence it was called.
    pkg_config("glib") {
    ^-------------------
  See //build/config/compiler/BUILD.gn:157:18: which caused the file to be included.
      configs += [ "//build/config/linux:compiler" ]
                   ^------------------------------
  GN gen failed: 1
Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/hab/pkgs/core/python2/2.7.12/20160926154224/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/hab/pkgs/core/python2/2.7.12/20160926154224/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
```

Stuck at the `do_build()` https://github.com/bdangit/hab-plans/blob/master/v8/plan.sh#L134

**Comment by bdangit** [comment]
Possibly complaining about glib package is missing.  Will need to see how to get it forced to use the hab core/glibc

**Comment by bdangit** [comment]
yep.. it is missing `glib` which is NOT `glibc` 🤕 

anyways got a plan brewing.

**Comment by bdangit** [comment]
this PR will close this issue. https://github.com/habitat-sh/core-plans/pull/226

**Comment by bdangit** [comment]
closing this since using bdangit/glib.
